AWSTemplateFormatVersion: "2010-09-09"
Resources:
  GithubActionsUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: permissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: cloudformation:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecs:*
                  - logs:*
                  - elasticloadbalancing:*
                  - ec2:Describe*
                Resource: "*"
              - Effect: Allow
                Action: s3:*
                Resource:
                  - !Sub arn:aws:s3:::stackit-*
                  - !Sub arn:aws:s3:::stackit-*/*
              - Effect: Allow
                Action: iam:*
                Resource: arn:aws:iam::*:role/test-stack-*
              - Effect: Allow
                Action: lambda:*
                Resource: arn:aws:lambda:*:*:function:test-stack-*
Outputs:
  GithubActionsUser:
    Value: !Ref GithubActionsUser
