AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  DockerImage:
    Type: String
    Default: nginx
  HealthCheckPath:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-8d2005e8
Resources:
  TaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Volumes: []
      Family: ecs-run-task-test
      ContainerDefinitions:
        - Name: ecs-run-task-test
          Image: !Ref DockerImage
          MemoryReservation: 256
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
                awslogs-group: !Ref LogGroup
                awslogs-region: !Ref AWS::Region
                awslogs-stream-prefix: MyCoolPrefix
#  Service:
#    Type: AWS::ECS::Service
#    Properties:
#      TaskDefinition: !Ref TaskDef
#      DesiredCount: 1
#      Cluster: Cluster
#      Role: !ImportValue EcsServiceRole
#      LoadBalancers:
#        - ContainerName: web
#          ContainerPort: 80
#          TargetGroupArn: !Ref TargetGroup
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: [TaskDef]
    Properties:
      HealthCheckIntervalSeconds: 60
      UnhealthyThresholdCount: 10
      HealthCheckPath: !Ref HealthCheckPath
      Port: 1234 # unused
      Protocol: HTTP
      VpcId: !Ref VpcId
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${AWS::StackName}-LogGroup
Outputs:
  LogGroup:
    Value: !Ref LogGroup
  TaskDef:
    Value: !Ref TaskDef
